merge_protections:
  - name: reviewed and green on main
    if:
      - base = main
    success_conditions:
      - base = main

queue_rules:
  - name: default
    merge_conditions:
      - base = main
    merge_method: squash
    batch_size: 1
